# Drastically increase swappiness because ZRAM is fast (CPU based)
# This encourages the kernel to compress idle code quickly.
vm.swappiness=100

# Increase cache pressure to reclaim inode/dentry memory faster
vm.vfs_cache_pressure=500

# Increase the time "dirty" data (waiting to be written to SD) stays in RAM.
# WHY: Groups writes together to save SD card wear.
vm.dirty_writeback_centisecs=1500
